// THIS FILE IS AUTO-GENERATED by Firebase CLI
// Run: flutterfire configure
// Then replace this file with the generated one

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web not supported');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHBAltmyhJ2f5-MwQkZQ9WhlqjPZrvUQ',
    appId: '1:149174171800:android:fcff803833d373bcf778ed',
    messagingSenderId: '149174171800',
    projectId: 'roadsos-a3000',
    storageBucket: 'roadsos-a3000.firebasestorage.app',
  );

  // Run: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.roadsos.app',
  );
}